### ISSUE TITLE
Facing error while deploying setup.

### ISSUE THREAD

**Issue by jaswant-dnv** [github-copilot-resources/copilot-metrics-viewer#106]

**Comment by jaswant-dnv** [comment]
Facing error while deploying setup
r# npm run serve

> copilot-metrics-viewer@1.6.0 serve
> vue-cli-service serve

 ERROR  Error loading vue.config.js:
 ERROR  TypeError: defineConfig is not a function
TypeError: defineConfig is not a function
    at Object.<anonymous> (/mnt/c/Users/JASWSI/Desktop/DnV/Work/Adam_ADO_Github-Handover/Github/CoPilot/APIMetrics/copilot-metrics-viewer/copilot-metrics-viewer/vue.config.js:2:18)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
    at Module.load (node:internal/modules/cjs/loader:1317:32)
    at Module._load (node:internal/modules/cjs/loader:1127:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1339:12)
    at require (node:internal/modules/helpers:135:16)
    at Service.loadUserOptions (/mnt/c/Users/JASWSI/Desktop/DnV/Work/Adam_ADO_Github-Handover/Github/CoPilot/APIMetrics/copilot-metrics-viewer/copilot-metrics-viewer/node_modules/@vue/cli-service/lib/Service.js:316:22)
    
    
    r# cat vue.config.js
const { defineConfig } = require('@vue/cli-service')
module.exports = defineConfig({
  transpileDependencies: true,

  pluginOptions: {
    vuetify: {
                        // https://github.com/vuetifyjs/vuetify-loader/tree/next/packages/vuetify-loader
                }
  }
})

**Comment by karpikpl** [comment]
Hi @jaswant-dnv 
can you provide details for your environment? node, npm versions? windows/linux?

Are you running version 1.6?

I've tested 1.6 tag on Linux and Windows just now and worked on both platforms.
It seems like you're using WSL but run windows file system from Linux, which is not recommended

**Comment by jaswant-dnv** [comment]
Yes we are using WSL
Ubuntu 20.04.6 LTS (GNU/Linux 5.15.153.1-microsoft-standard-WSL2 x86_64)
jas@PUNL200648:~$ uname -a
Linux PUNL200648 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
jas@PUNL200648:~$ wslinfo --wsl-version
2.3.24
jas@PUNL200648:~$

I will test this again on ubuntu machine.

**Comment by karpikpl** [comment]
if you could share output of
```
node --version
npm --version
```

you can also try building docker image - if that works, it means the issue is most likely local

**Comment by jaswant-dnv** [comment]
root# npm --version
10.9.0
root node --v
ersion
v22.9.0


Yeah Will try building docker image for test.

**Comment by jaswant-dnv** [comment]
Issue was not due to wsl but the ubuntu version we were using.
upgraded from 20.04 to 22.04 and it fixed issue.
Able to setup this locally.

Will Build container image for prod setup.

**Comment by karpikpl** [comment]
thanks for the follow up and closing the issue!
